name: image builder

on:
  push:
    branches: [ main ]

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login do docker.io
      run: docker login -u odidev -p nibble@123

    - name: Build and push amd64 image
      uses: docker/build-push-action@v4
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: odidev/kepler
          labels: latest-amd64
          file: build/Dockerfile.builder
          build-args: |
            TAG=amd64
    - name: Build and push arm64 image
      uses: docker/build-push-action@v4
      with:
          context: .
          platforms: linux/arm64
          push: true
          tags: odidev/kepler
          labels: latest-arm64
          file: build/Dockerfile.builder
          build-args: |
            TAG=arm64
